apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadwsvx3257-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadwsvx3257-tenant-component
    app.kubernetes.io/part-of: loadwsvx3257-tenant-app
  name: loadwsvx3257-tenant-component
  namespace: loadwsvx3257-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadwsvx3257-tenant-component
status:
  loadBalancer: {}
